name: Dev
on:
  push:
  pull_request:
env:
  DD_TIME: ""
jobs:
  ubuntu-dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - name: Compile
        run: |
          echo "DD_TIME=DD-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update && sudo apt-get install libfuse2 intel-oneapi-mkl-devel
          mkdir build && cd build
          source /opt/intel/oneapi/setvars.sh
          cmake -S .. -B . -DCMAKE_BUILD_TYPE=release -DDD_USE_TBB=ON
          make -j"$(nproc)"
          wget -q https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage
          mkdir deploy && cd deploy
          cp ../damping-dolphin .
          ../linuxdeployqt-continuous-x86_64.AppImage damping-dolphin -bundle-non-qt-libs -unsupported-allow-new-glibc -no-translations
          ls -alt
          tar -czf ../../damping-dolphin-linux.tar.gz *
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: damping-dolphin-linux.tar.gz
          path: damping-dolphin-linux.tar.gz
      - name: Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: damping-dolphin-linux.tar.gz
          asset_name: damping-dolphin-linux.tar.gz
          tag: ${{ env.DD_TIME }}
          prerelease: true
          overwrite: true
